# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='excludes',
            field=models.TextField(blank=True, help_text='seperate each item by coma', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='contents',
            field=models.TextField(default='a', help_text='seperate each item by coma'),
            preserve_default=False,
        ),
    ]
